## MATRIX OPERATION

In [1]:
import numpy as np

In [2]:
A=np.array([[2,-1],[0,3]])
B=np.array([[1,2],[-3,4]])
print("Matrix A is ")
print(A)
print("Matrix B is")
print(B)
print("The sum of A and B")
print(A+B)
print("The product of A and B")
print(A @ B)
print("Result of 3A-2B")
print(3*A-2*B)

Matrix A is 
[[ 2 -1]
 [ 0  3]]
Matrix B is
[[ 1  2]
 [-3  4]]
The sum of A and B
[[ 3  1]
 [-3  7]]
The product of A and B
[[ 5  0]
 [-9 12]]
Result of 3A-2B
[[ 4 -7]
 [ 6  1]]


## Determinant of a Matrix

In [3]:
import numpy.linalg as LA

In [4]:
A=np.array([[2,-1],[0,3]])
LA.det(A)

np.float64(6.0)

## Inverse of a matrix

In [6]:
if(LA.det(A)!=0):
    print("A is invertible")
    A_inv=np.linalg.inv(A)
    print("Inverse of matrix A ")
    print(A_inv)
else:
    print("A is not invertible")

A is invertible
Inverse of matrix A 
[[0.5        0.16666667]
 [0.         0.33333333]]


## Eigen Values And Eigen Vectors

In [7]:
C=np.array([[4,1],[-2,1]])
print("Matrix C is")
print(C)
eigenvalues,eigenvectors=np.linalg.eig(A)
print("Eigenvalue(first)")
print(eigenvalues[0])
print("Corresponding eigenvector is ")
print(eigenvectors[:, 0])
print("Eigenvalue(second)")
print(eigenvalues[1])
print("Corresponding eigenvector is ")
print(eigenvectors[:, 1])

Matrix C is
[[ 4  1]
 [-2  1]]
Eigenvalue(first)
2.0
Corresponding eigenvector is 
[1. 0.]
Eigenvalue(second)
3.0
Corresponding eigenvector is 
[-0.70710678  0.70710678]


# To calculate the price of a car 

In [8]:
print("The Feature Matrix is")
X=np.array([
    [4,1.5,100],
    [6,2,150]
])
print(X)
print("Price Vector")
y=np.array([
    [20],
    [30]
])
print(y)
# computing coefficient using pseudo inverse
beta=np.linalg.pinv(X).dot(y)
#To find the price of car3
print("Feature Matrix of car3")
X1=np.array([
    [8,3,200]
])
print(X1)
priceofcar3= X1 @ beta
print("The price of car 3 is")
print(priceofcar3)

The Feature Matrix is
[[  4.    1.5 100. ]
 [  6.    2.  150. ]]
Price Vector
[[20]
 [30]]
Feature Matrix of car3
[[  8   3 200]]
The price of car 3 is
[[40.]]
